apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./base

commonLabels:
  app: {{ cookiecutter.app_label }}
  owner: {{ cookiecutter.owner_label }}
  version: {{ cookiecutter.app_version }}

generatorOptions:
  annotations:
    note: generated
  disableNameSuffixHash: false
  labels:
    team: {{ cookiecutter.team_label }}
    type: generated
