apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ cookiecutter.app_name }}-config
data:
  # Application configuration
  APP_NAME: {{ cookiecutter.app_name }}
  EXTRA_DUMMY: VALUE

  # Environment-specific values will be added here
  # Add your configuration values below
  # DATABASE_HOST: "your-database-host"
  # REDIS_URL: "redis://redis:6379"
  # LOG_LEVEL: "info"
