{% if cookiecutter.autoscaling_enabled == 'true' %}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ cookiecutter.app_name }}
  labels:
    app: {{ cookiecutter.app_label }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ cookiecutter.app_name }}
  minReplicas: {{ cookiecutter.autoscaling_minReplicas }}
  maxReplicas: {{ cookiecutter.autoscaling_maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ cookiecutter.autoscaling_targetCPUUtilizationPercentage }}
status:
  currentReplicas: 0
  desiredReplicas: 0
{% endif %}
