{% if cookiecutter.poddisruptionbudget_enabled == 'true' %}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ cookiecutter.app_name }}
  labels:
    app: {{ cookiecutter.app_label }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ cookiecutter.app_label }}
{% endif %}
