apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cookiecutter.app_name }}
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: {{ cookiecutter.app_name }}
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: LOG_LEVEL
              value: "debug"
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi
