apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
  - ./deployment-patch.yaml
{% if cookiecutter.httproute_enabled == 'true' -%}
  - ./httproute-patch.yaml
{% endif -%}
resources:
  - ../../base/

images:
  - name: {{ cookiecutter.image_repository }}
    newTag: dev

commonLabels:
  app: {{ cookiecutter.app_label }}
  owner: {{ cookiecutter.owner_label }}
  environment: dev

generatorOptions:
  annotations:
    note: generated
    environment: dev
  disableNameSuffixHash: true
  labels:
    team: {{ cookiecutter.team_label }}
    type: generated
    environment: dev
